<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify Document - {{ $doc_id }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f1f5f9; color: #334155; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .card { background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1); max-width: 500px; width: 100%; text-align: center; }
        .success-icon { color: #16a34a; margin-bottom: 20px; }
        h1 { margin-top: 0; color: #1e293b; font-size: 24px; }
        .details { text-align: left; background: #f8fafc; padding: 20px; border-radius: 8px; margin-top: 20px; border: 1px solid #e2e8f0; }
        .details p { margin: 8px 0; font-size: 15px; }
        .details strong { color: #0f172a; }
        .footer { margin-top: 30px; font-size: 13px; color: #64748b; }
    </style>
</head>
<body>
    <div class="card">
        <div class="success-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                <polyline points="22 4 12 14.01 9 11.01"></polyline>
            </svg>
        </div>
        <h1>Document Verified</h1>
        <p>This document is authentic and generated by TechFocal WMS.</p>
        
        <div class="details">
            <p><strong>Document Type:</strong> {{ $typeLabel }}</p>
            <p><strong>Document ID:</strong> {{ $doc_id }}</p>
            <p><strong>Generated On:</strong> {{ $doc->created_at->format('d M Y, h:i A') }}</p>
            <p><strong>Status:</strong> <span style="color: #16a34a; font-weight: bold;">Valid</span></p>
        </div>
        
        <div class="footer">
            &copy; {{ date('Y') }} TechFocal Enterprises LLP. All rights reserved.
        </div>
    </div>
</body>
</html>
